services:
  - type: web
    name: prime-label-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI_PROD
        sync: false # This will be set manually in Render dashboard
    autoDeploy: true
